icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]



[[block]]
block = "bluetooth"
mac = "88:C9:E8:E8:5B:35"
format = " {$icon $name $percentage |bluetooth }"
[[block.click]]
button = "left"
cmd = "foot bluetuith"

[[block]]
block = "net"
format = " $icon $signal_strength $ssid "
inactive_format = " $icon Down "
[[block.click]]
button = "left"
cmd = "foot nmtui-connect"


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
[[block.click]]
button = "left"
cmd = "foot btop"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[[block.click]]
button = "left"
cmd = "foot btop"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"
[block.mappings]
"English (US)" = "US"
"German (Switzerland)" = "CH"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block="backlight"

[[block]]
block = "battery"
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
